connector.name=kafka
kafka.nodes=kafka:29092
kafka.default-schema=default
kafka.table-description-supplier=FILE
kafka.table-description-dir=/etc/trino/kafka

# Add your mapped topics here. You can use either table names or schema-qualified table names.
kafka.table-names=default.buswaypoint_json
