apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: buswaypoints
  namespace: data-platform
  labels:
    strimzi.io/cluster: data-platform-kafka
spec:
  partitions: 3
  replicas: 2
  config:
    retention.ms: 604800000
    segment.bytes: 1073741824
